### ISSUE TITLE
This project need  mobile Magnetic Sensor?

### ISSUE THREAD

**Issue by 40943260** [BlueBunnex/StellarVR#1]
excuse me.
my mobile is (motorola g50) .
It not have magnetic sensor but it have gyroscope.
I try Demo scene on motorola g50 but not work.
Does it not work because there is no Magnetic Sensor?

**Comment by dairycultist** [comment]
I'll see if I can look into this problem soon, however I'm not sure I can help you. I don't own a motorola (I use a google pixel, which does have a magnetic sensor, though I don't believe Unity utilizes that for finding the device's orientation) and so can't test it myself.

If you want to know if the project could work for you, you may want to test if [Unity's Input.gyro](https://docs.unity3d.com/ScriptReference/Input-gyro.html) gives you correct output on your phone. There is a demo script on that page that you can use to test this. If it so happens that Unity doesn't support gyroscope on your phone, there's not much I can do.

Hope that helps~

**Comment by 40943260** [comment]
m_Gyro.attitude value not change。
maybe m_Gyro.attitude need Magnetic Sensor。
Looks like I need to get a better phone。
Thank you for your reply。
